services:
  app:
    build: .
    command: ["uvicorn", "--host", "0.0.0.0", "--reload", "--factory", "app.main:create_app"]
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    healthcheck:
      test: curl localhost:8000/healthz || exit 1
      timeout: 2s
      interval: 3s

  db:
    image: postgres:16.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigtrip
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username user -d bigtrip || exit 1
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  pg_data:
